CREATE INDEX suppliers_phone_idx ON public.suppliers USING btree (phone_e164);
CREATE INDEX idx_outbox_channel_time ON public.whatsapp_outbox USING btree (channel_id, created_at DESC);
CREATE INDEX idx_sales_rows_product ON public.sales_rows USING btree (product_id);
CREATE INDEX idx_audit_org_time ON public.audit_log USING btree (org_id, created_at DESC);
CREATE INDEX idx_purchase_orders_status ON public.purchase_orders USING btree (org_id, status);
CREATE INDEX idx_suggestions_org ON public.suggestions USING btree (org_id);
CREATE INDEX idx_pos_delivered_at ON public.purchase_orders USING btree (delivered_at);
CREATE INDEX ix_sales_uploads_org_time ON public.sales_uploads USING btree (org_id, uploaded_at DESC);
CREATE INDEX idx_outbox_status_next_attempt ON public.whatsapp_outbox USING btree (status, next_attempt_at, created_at);
CREATE INDEX idx_inquiries_supplier ON public.inquiries USING btree (org_id, supplier_id, status);
CREATE INDEX idx_suggestions_scope ON public.suggestions USING btree (org_id, store_id, supplier_id, product_id);
CREATE INDEX idx_suggestions_pending ON public.suggestions USING btree (org_id, created_at DESC) WHERE (status = 'PENDING'::suggestion_status);
CREATE INDEX idx_suggestions_status ON public.suggestions USING btree (status);
CREATE INDEX idx_inventory_snapshots_recorded_at ON public.inventory_snapshots USING btree (recorded_at);
CREATE INDEX idx_poi_po ON public.purchase_order_items USING btree (po_id);
CREATE UNIQUE INDEX uq_channel_whatsapp_phone ON public.channel_whatsapp USING btree (phone_number_id);
CREATE INDEX idx_audit_created ON public.audit_log USING btree (created_at);
CREATE INDEX admin_messages_org_id_idx ON public.admin_messages USING btree (org_id);
CREATE INDEX idx_inventory_snapshots_product ON public.inventory_snapshots USING btree (product_id);
CREATE INDEX idx_outbox_org_time ON public.whatsapp_outbox USING btree (org_id, created_at DESC);
CREATE INDEX ix_stock_uploads_org_time ON public.stock_uploads USING btree (org_id, uploaded_at DESC);
CREATE INDEX idx_sales_rows_recorded_at ON public.sales_rows USING btree (recorded_at);
CREATE INDEX idx_outbox_status_created ON public.whatsapp_outbox USING btree (status, created_at);
